name: toxic
channels:
- conda-forge
- defaults
- anaconda
dependencies:
# shell
- ipython
- jupyter
- jupyterlab
- pip
- python=3
# visualization
- matplotlib
- wordcloud
# general data analysis
- numpy
- pandas
- pandas-gbq=0.3.*
- scikit-learn
- scipy
- seaborn
- statsmodels
# NLP
- nltk
- textblob
