name: twotoxic
channels:
- conda-forge
- defaults
- anaconda
dependencies:
- google-api-python-client
- ipython
- jupyter
- jupyterlab
- matplotlib
- nltk
- numpy
- pandas
- pandas-gbq
- pip
- python>=3.5.4
- scikit-learn
- scipy
- seaborn
- statsmodels
- textblob
- wordcloud
